// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// AN_test
List AN_test(NumericMatrix X, NumericMatrix Y, LogicalVector na_rm, LogicalVector pool, NumericVector poolVarX, NumericVector poolVarY);
RcppExport SEXP tan_AN_test(SEXP XSEXP, SEXP YSEXP, SEXP na_rmSEXP, SEXP poolSEXP, SEXP poolVarXSEXP, SEXP poolVarYSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type X(XSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type Y(YSEXP);
    Rcpp::traits::input_parameter< LogicalVector >::type na_rm(na_rmSEXP);
    Rcpp::traits::input_parameter< LogicalVector >::type pool(poolSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type poolVarX(poolVarXSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type poolVarY(poolVarYSEXP);
    rcpp_result_gen = Rcpp::wrap(AN_test(X, Y, na_rm, pool, poolVarX, poolVarY));
    return rcpp_result_gen;
END_RCPP
}
// compute_Var
List compute_Var(NumericMatrix X, NumericMatrix Y, LogicalVector na_rm, LogicalVector pool);
RcppExport SEXP tan_compute_Var(SEXP XSEXP, SEXP YSEXP, SEXP na_rmSEXP, SEXP poolSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type X(XSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type Y(YSEXP);
    Rcpp::traits::input_parameter< LogicalVector >::type na_rm(na_rmSEXP);
    Rcpp::traits::input_parameter< LogicalVector >::type pool(poolSEXP);
    rcpp_result_gen = Rcpp::wrap(compute_Var(X, Y, na_rm, pool));
    return rcpp_result_gen;
END_RCPP
}
// timesTwo
int timesTwo(int x);
RcppExport SEXP tan_timesTwo(SEXP xSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< int >::type x(xSEXP);
    rcpp_result_gen = Rcpp::wrap(timesTwo(x));
    return rcpp_result_gen;
END_RCPP
}
