# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Compute the adaptive Neyman test
#'
#' @param X A coverage vector for first condition
#' @param Y A coverage vector for second condition
#' @param na_rm TRUE to remove NA values
#' @param pool TRUE if variance is pooled. In this case, pre-computed poolVarX and poolVarY must be provided.
#'    If FALSE, pointwise variance is computed.
#' @param poolVarX A precomputed variance vector from the first condition. The pooled variance is implemented
#'    according to our paper.
#' @param poolVarY A precomputed variance vector from the second condition. The pooled variance is implemented
#'    according to our paper.
#' @export
AN_test <- function(X, Y, na_rm, pool, poolVarX, poolVarY) {
    .Call('tan_AN_test', PACKAGE = 'tan', X, Y, na_rm, pool, poolVarX, poolVarY)
}

#' Compute the variance vector
#'
#' @param X a coverage vector for first condition
#' @param Y a coverage vector for second condition
#' @param na_rm TRUE to remove NA values
#' @param pool TRUE if variance is pooled; FALSE if pointwise variance is computed.
#'    For the current implementation, only case pool = FALSE is considered.
#' @export
compute_Var <- function(X, Y, na_rm, pool) {
    .Call('tan_compute_Var', PACKAGE = 'tan', X, Y, na_rm, pool)
}

